export const CREATE_RECORD = 'CREATE_RECORD';
export const UPDATE_STORE_VALUES = 'UPDATE_STORE_VALUES';
export const DELETE_RECORD = 'DELETE_RECORD';
export const SET_LIST_RECORDS = 'SET_LIST_RECORDS';
export const FEED_LIST_OF_COUNTRIES = 'FEED_LIST_OF_COUNTRIES';
export const EDIT_RECORD = 'EDIT_RECORD';
export const CLICK_ON_FRIEND_RECORD = 'CLICK_ON_FRIEND_RECORD';
